#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPRO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GSport")]
	public partial class GsportDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GsportDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GSportConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GsportDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GsportDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GsportDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GsportDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Price_View")]
		public ISingleResult<Price_ViewResult> Price_View([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipe", DbType="VarChar(5)")] string tipe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tanggal", DbType="VarChar(10)")] string tanggal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KodeSchedule", DbType="VarChar(50)")] string kodeSchedule)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tipe, tanggal, kodeSchedule);
			return ((ISingleResult<Price_ViewResult>)(result.ReturnValue));
		}
	}
	
	public partial class Price_ViewResult
	{
		
		private string _KodeHari;
		
		private string _Schedule;
		
		private System.Nullable<decimal> _Price;
		
		public Price_ViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KodeHari", DbType="VarChar(50)")]
		public string KodeHari
		{
			get
			{
				return this._KodeHari;
			}
			set
			{
				if ((this._KodeHari != value))
				{
					this._KodeHari = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schedule", DbType="VarChar(13)")]
		public string Schedule
		{
			get
			{
				return this._Schedule;
			}
			set
			{
				if ((this._Schedule != value))
				{
					this._Schedule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
