<?xml version="1.0" encoding="utf-8"?><Database Name="GSport" Class="GsportDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KLDIT18\SQLEXPRESS;Initial Catalog=GSport;Persist Security Info=True;User ID=sa" SettingsObjectName="CORE.COMPRO.Properties.Settings" SettingsPropertyName="GSportConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Price_View" Method="Price_View">
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Tanggal" Parameter="tanggal" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="KodeSchedule" Parameter="kodeSchedule" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Price_ViewResult">
      <Column Name="KodeHari" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Schedule" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>